services:
  nginx:
    container_name: cinema-rev-proxy
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
     - app
  app:
    build: .
    expose:
      - 8080
  db:
    container_name: cinema_database
    image: postgres:18-alpine
    env_file:
       - .env
    ports:
      - 8000:5432 # TODO: zmień na expose na produkcji
    volumes:
      - pgdata:/var/lib/posgresql

volumes:
  pgdata: